server:
  port: 9296

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zaurjabrailov77/MicroservicesArchitectureConfigServer
          clone-on-start: true

#          uri: https://github.com/zaurjabrailov77/cloud-config-server
# bu github in ozunden oxuyur yml file bele ishdemedi baxarsan

#      uri: E:/JAVA_LESSONS/GitHubProjects/AllSpring/MicroservicesUsingSpringBoot/cloud-config-server/cloud-config-server